### ISSUE TITLE
Source code unavailable

### ISSUE THREAD

**Issue by capt-prateek** [MicrochipTech/bm83_getting_started#1]
Hello,

I tried to download the source code from the available link (http://ww1.microchip.com/downloads/en/DeviceDoc/IS2083%20Software%20&%20Tools%20(v1.0.3).zip). When I navigated to the folder that should contain the source codes for both Android and iOS, I found the files with the .exe extension. This is a windows extension for installing software. It can't work on an Apple Macbook. For the windows system too, the android code can't be with the .exe extension. Could you please add the source codes with proper files and extensions?

Thanks,
PC

**Comment by gd91** [comment]
updated link
